### ISSUE TITLE
What is the purpose of measuredPower?

### ISSUE THREAD

**Issue by fcrespo82** [watr/mbeacon#1]
My beacon is triggering very far from the location where the Mac is.

How can I adjust the measuredPower to trigger when I'm like 10 feet away?

**Comment by watr** [comment]
You can't adjust Mac's bluetooth signal strength by ```measuredPower```  value. That value is used as information in iBeacon's advertising packet.

**Comment by watr** [comment]
I've updated [README](https://github.com/watr/mbeacon/blob/master/README.md).

**Comment by fcrespo82** [comment]
This helped me a lot! Thanks for the clarification!
